apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: grafana
    jsonData:
      database: telemetry
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: grafana_dev
    editable: true
    isDefault: true
