apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: ${TS_DATASOURCE_URL:-timescaledb:5432}
    user: ${TS_DATASOURCE_USER:-postgres}
    jsonData:
      database: ${TS_DATASOURCE_DB:-telemetry}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: ${TS_DATASOURCE_PASSWORD:-postgres}
    editable: true
    isDefault: true
